/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Osvaldo08CR
 */
public class AdministratorCreateEdit extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorCreateEdit
     */
    public AdministratorCreateEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schedule Generator - Create/Edit Professors, Courses and Classrooms");
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jTabbedPane2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 20, 30);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 40, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Added courses");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 180, 90, 30);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 30, 210, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Engeneer", "Bussiness Administration", "Industrial Engeneer" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(80, 130, 210, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(80, 80, 540, 30);

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton1.setText("Add");
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 380, 60, 30);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel10.setText("Feedback");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 430, 670, 30);

        jButton4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton4.setText("Clear");
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 380, 70, 30);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 430, 680, 10);

        jList1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 290, 150);

        jLabel31.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("School:");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(20, 130, 50, 30);

        jList2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 210, 290, 150);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right.png"))); // NOI18N
        jPanel1.add(jButton10);
        jButton10.setBounds(320, 250, 40, 25);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(320, 290, 40, 25);

        jLabel32.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Total courses");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(20, 180, 80, 30);

        jTabbedPane2.addTab("Professor", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 110, 30, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 150, 39, 30);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Credits:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 190, 50, 30);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Support material:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 270, 110, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jCheckBox1.setText("Exclusive:  ");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(50, 230, 110, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Practical");
        jRadioButton1.setPreferredSize(new java.awt.Dimension(79, 31));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jRadioButton2.setText("Theorical");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jRadioButton2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 10, 300, 70);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Operative System:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 310, 120, 30);

        jTextField3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(140, 110, 160, 30);

        jTextField4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(140, 150, 450, 30);

        jTextField5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(140, 190, 50, 30);

        jTextField6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(140, 270, 450, 30);

        jTextField7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(140, 310, 450, 30);

        jButton2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton2.setText("Add");
        jPanel2.add(jButton2);
        jButton2.setBounds(520, 350, 70, 30);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel9.setText("Feedback");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 430, 660, 30);

        jButton3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton3.setText("Clear");
        jPanel2.add(jButton3);
        jButton3.setBounds(440, 350, 70, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 430, 680, 10);

        jTabbedPane2.addTab("Course", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ID:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(50, 30, 20, 30);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Name:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 80, 40, 30);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Location:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 130, 60, 30);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Capacity:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 180, 60, 30);

        jTextField8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel3.add(jTextField8);
        jTextField8.setBounds(80, 30, 210, 30);

        jTextField9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel3.add(jTextField9);
        jTextField9.setBounds(80, 80, 540, 30);

        jTextField10.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel3.add(jTextField10);
        jTextField10.setBounds(80, 130, 540, 30);

        jTextField11.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel3.add(jTextField11);
        jTextField11.setBounds(80, 180, 60, 30);

        jButton5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton5.setText("Add");
        jPanel3.add(jButton5);
        jButton5.setBounds(550, 220, 70, 30);

        jButton6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton6.setText("Clear");
        jPanel3.add(jButton6);
        jButton6.setBounds(470, 220, 70, 30);

        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel15.setText("Feedback");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 430, 660, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 430, 680, 10);

        jTabbedPane2.addTab("Classroom", jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Create", jPanel6);

        jTabbedPane3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);
        jPanel4.add(jSeparator6);
        jSeparator6.setBounds(0, 430, 680, 10);

        jLabel16.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel16.setText("Feedback");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 430, 670, 30);

        jLabel19.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("ID:");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(50, 30, 20, 30);

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(80, 30, 210, 30);

        jLabel20.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Name:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 80, 40, 30);

        jLabel21.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("School:");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(20, 130, 50, 30);

        jTextField12.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel4.add(jTextField12);
        jTextField12.setBounds(80, 80, 540, 30);

        jComboBox3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(80, 130, 210, 30);

        jButton7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton7.setText("Save");
        jPanel4.add(jButton7);
        jButton7.setBounds(550, 390, 70, 30);

        jLabel33.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Professor courses");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(20, 180, 110, 30);

        jLabel34.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Total courses");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(370, 180, 80, 30);

        jList3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList3);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 210, 290, 150);

        jList4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(370, 210, 290, 150);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right.png"))); // NOI18N
        jPanel4.add(jButton12);
        jButton12.setBounds(320, 250, 40, 25);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left.png"))); // NOI18N
        jPanel4.add(jButton13);
        jButton13.setBounds(320, 290, 40, 25);

        jTabbedPane3.addTab("Professor", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);
        jPanel8.add(jSeparator5);
        jSeparator5.setBounds(0, 430, 680, 10);

        jLabel17.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel17.setText("Feedback");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(10, 430, 670, 30);

        jLabel22.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("ID:");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(50, 30, 20, 30);

        jComboBox4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel8.add(jComboBox4);
        jComboBox4.setBounds(80, 30, 210, 30);

        jLabel23.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Name:");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(90, 90, 39, 30);

        jLabel24.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Credits:");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(80, 130, 50, 30);

        jLabel25.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Support material:");
        jPanel8.add(jLabel25);
        jLabel25.setBounds(20, 210, 110, 30);

        jLabel26.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Operative System:");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(10, 250, 120, 30);

        jCheckBox2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jCheckBox2.setText("Exclusive:  ");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel8.add(jCheckBox2);
        jCheckBox2.setBounds(60, 170, 100, 31);

        jTextField13.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel8.add(jTextField13);
        jTextField13.setBounds(140, 90, 450, 30);

        jTextField14.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel8.add(jTextField14);
        jTextField14.setBounds(140, 130, 50, 30);

        jTextField15.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel8.add(jTextField15);
        jTextField15.setBounds(140, 210, 450, 30);

        jTextField16.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel8.add(jTextField16);
        jTextField16.setBounds(140, 250, 450, 30);

        jButton8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton8.setText("Save");
        jPanel8.add(jButton8);
        jButton8.setBounds(520, 300, 70, 30);

        jTabbedPane3.addTab("Course", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);
        jPanel9.add(jSeparator4);
        jSeparator4.setBounds(0, 430, 680, 10);

        jLabel18.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel18.setText("Feedback");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(10, 430, 670, 30);

        jLabel27.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("ID:");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(50, 30, 20, 30);

        jComboBox5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel9.add(jComboBox5);
        jComboBox5.setBounds(80, 30, 210, 30);

        jLabel28.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Name:");
        jPanel9.add(jLabel28);
        jLabel28.setBounds(30, 80, 40, 30);

        jLabel29.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Location:");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(10, 130, 60, 30);

        jLabel30.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Capacity:");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(10, 180, 60, 30);

        jTextField17.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel9.add(jTextField17);
        jTextField17.setBounds(80, 80, 540, 30);

        jTextField18.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel9.add(jTextField18);
        jTextField18.setBounds(80, 130, 540, 30);

        jTextField19.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel9.add(jTextField19);
        jTextField19.setBounds(80, 180, 60, 30);

        jButton9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton9.setText("Save");
        jPanel9.add(jButton9);
        jButton9.setBounds(550, 220, 70, 30);

        jTabbedPane3.addTab("Classroom", jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Edit", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 30, 750, 510);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jMenuItem1.setText("Administrator Shedule");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jMenuItem3.setText("Administrator Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jMenuItem2.setText("Back to Login");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Open de Administrator Schedule window.
        this.dispose();
        new AdministratorSchedule().show(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Open de Login window.
        this.dispose();
        new Login().show(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Open de Administrator Menu window.
        this.dispose();
        new AdministratorMenu().show(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorCreateEdit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
